<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWl3xIPH\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWl3xIPH/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWl3xIPH.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWl3xIPH\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWl3xIPH\App_KernelProdContainer([
    'container.build_hash' => 'Wl3xIPH',
    'container.build_id' => 'a0e6eec6',
    'container.build_time' => 1593897554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWl3xIPH');
