<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTxFrKiA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTxFrKiA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTxFrKiA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTxFrKiA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTxFrKiA\App_KernelDevDebugContainer([
    'container.build_hash' => 'TxFrKiA',
    'container.build_id' => '6bbcb204',
    'container.build_time' => 1594105490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTxFrKiA');
