<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKJM784y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKJM784y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKJM784y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKJM784y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKJM784y\App_KernelDevDebugContainer([
    'container.build_hash' => 'KJM784y',
    'container.build_id' => '6f1251fc',
    'container.build_time' => 1592978543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKJM784y');
