<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offres extends \App\Entity\Offres implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'Intitule', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'DateDebut', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'DateFin', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'CahierDesCharges', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'Entreprise', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'apprenant'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'Intitule', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'DateDebut', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'DateFin', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'CahierDesCharges', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'Entreprise', '' . "\0" . 'App\\Entity\\Offres' . "\0" . 'apprenant'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offres $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntitule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntitule', []);

        return parent::getIntitule();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntitule(string $Intitule): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntitule', [$Intitule]);

        return parent::setIntitule($Intitule);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(\DateTimeInterface $DateDebut): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$DateDebut]);

        return parent::setDateDebut($DateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(\DateTimeInterface $DateFin): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$DateFin]);

        return parent::setDateFin($DateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCahierDesCharges(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCahierDesCharges', []);

        return parent::getCahierDesCharges();
    }

    /**
     * {@inheritDoc}
     */
    public function setCahierDesCharges(?string $CahierDesCharges): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCahierDesCharges', [$CahierDesCharges]);

        return parent::setCahierDesCharges($CahierDesCharges);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise(): ?\App\Entity\Entreprise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', []);

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise(?\App\Entity\Entreprise $Entreprise): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', [$Entreprise]);

        return parent::setEntreprise($Entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getApprenant(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprenant', []);

        return parent::getApprenant();
    }

    /**
     * {@inheritDoc}
     */
    public function addApprenant(\App\Entity\Apprenant $apprenant): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApprenant', [$apprenant]);

        return parent::addApprenant($apprenant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApprenant(\App\Entity\Apprenant $apprenant): \App\Entity\Offres
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApprenant', [$apprenant]);

        return parent::removeApprenant($apprenant);
    }

}
